### ISSUE TITLE
command help documentation is incomplete

### ISSUE THREAD

**Issue by xubiod** [xubiod/xubot#2]
only has like half of the commands (more precisely 57ish)

**Comment by WamWooWam** [comment]
Would it be an idea to automatically generate this rather than have it all hard coded? Something like [this](https://github.com/WamWooWam/WamBot/blob/rewrite/WamBotRewrite/Commands/StockCommands.cs#L366)?

**Comment by xubiod** [comment]
@WamWooWam what i mean is in the documentation [to appear here.](https://xubot-team.github.io/xubot/help) it could be generated for the help command, yet the page system might cause some issues.

**Comment by xubiod** [comment]
closed for future reasons to discuss
