### ISSUE TITLE
[Feature] Github release update

### ISSUE THREAD

**Issue by NicoCG** [xubiod/xubot#7]
Why download latest release from ftp server if you can do so directly from GitHub release see links below.

https://github.com/thoemmi/Solutionizer/blob/master/Solutionizer/Infrastructure/ReleaseInfoReader.cs

And

https://github.com/thoemmi/Solutionizer/blob/master/Solutionizer/Infrastructure/UpdateManager.cs

**Comment by xubiod** [comment]
I'll look into which method is the best for the project.

There are specific files required for the operation of the bot (like API keys and tokens) which are always provided with the FTP method I have.

**Comment by NicoCG** [comment]
Cool, the same files could be included within the releases zip, once it downloaded with the method above it installs. Just thought it will be cool every time there is a new release enduser will be able download it on there server directly from GitHub. Files like .json only if there is change it will override it I suggest you keep old-json file so user can revert if needed.
